http:
  ip: 0.0.0.0
  port: 8081
  # debug、test、release
  mode: debug
mysql:
  dsn: "lll-server:123456789@tcp(192.168.179.134:3306)/ai_transform?collation=utf8mb4_unicode_ci&charset=utf8mb4"
  maxLifeTime: 3600
  maxOpenConn: 10
  maxIdleConn: 10
externalKafka:
  user: admin
  pwd: 123456
  saslMechanism: PLAIN
  maxRetry: 3
  address:
    - 192.168.179.134:59092
kafka:
  user: admin
  pwd: 123456
  saslMechanism: PLAIN
  maxRetry: 3
  address:
    - 192.168.179.134:29092
    - 192.168.179.134:39092
    - 192.168.179.134:49092
log:
  # panic,fatal,error,warn,warning,info,debug,trace
  level: "debug"
  logPath: "runtime/logs/app.log"
cos:
  secretId: AKIDTyLWUFoBLI2auztPo01pRVO4Yos0yqgO
  secretKey: 6zf8ORHwOehhaHm49h3Qeo2AJMeppdFf
  region: "ap-guangzhou"
  appID: "1407920408"
  bucket: "transform-1407920408"
  cdnDomain: "https://transform-1407920408.cos.ap-guangzhou.myqcloud.com"
  bucketUrl: "https://transform-1407920408.cos.ap-guangzhou.myqcloud.com"
asr:
  secretId: AKIDnRuATZYLEvgLqGVYTCk7HH7oKLJ9rPpD
  secretKey: IPL5g7PWTIzZzLzRiHn9DAyb4UileNv1
  endpoint: "asr.tencentcloudapi.com"
  region: "ap-guangzhou"
  modals: ["啊","呃","哎","唉","呢","嗯"]
tmt:
  region: "ap-guangzhou"
  endpoint: "tmt.tencentcloudapi.com"
  secretID: "AKIDEUbaMzSlrLIm6Io8JJAwZ1HQO9lCQRJQ"
  secretKey: "5yiJJCsLdkeLqCLHpBMK5e0CBzb2NWSB"
dependOn:
  gpt:
    - http://localhost:9881
  referWav:
    address: "http://localhost:8085"
  user:
    address: "http://localhost:8082"
llm:
    apiKey: "sk-500aeda9598645a5a8ef09abc73cd0fe"
    baseURL: "https://api.deepseek.com/v1"
    model: "deepseek-chat"
    maxTokens: 2048
    temperature: 0.7
proofreadingTermsFile: "./proofreading_terms.yaml"